slam_toolbox:
  ros__parameters:

    use_sim_time: true

    mode: mapping
    slam_mode: true

    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan

    resolution: 0.05
    max_laser_range: 12.0

    minimum_travel_distance: 0.2
    minimum_travel_heading: 0.2

    transform_publish_period: 0.05
